-- Ordering hours per brand and per channel (Part 2 of the brands/hours/statuses round).
--
-- Before: one openingTime/closingTime per branch, plus two hardcoded platform
-- rules in code: everything closed 04:00-11:00 Dhaka, delivery's last order at
-- 03:45, and a Cheez-only "late-night delivery" extension past closing time.
-- After: BranchBrand.hours holds each brand's own schedule at each branch, with
-- Delivery and Pickup ticked per slot, and Branch.dineInHours holds display-only
-- dine-in hours. The old columns are dropped once converted.
--
-- The conversion reproduces what the code ENFORCED, per brand, so nothing that
-- could be ordered yesterday is refused today and nothing new opens:
--   * no hours set      -> 11:00-04:00, delivery + pickup (the platform window);
--   * daytime hours O-C -> max(O, 11:00) to C, both channels; for the Cheez brand
--     the slot runs on to 04:00, because the old late-night rule kept Cheez
--     orderable after closing until the platform closed;
--   * overnight / early-morning hours (the branch's own hours were authoritative
--     in the old code) -> O to C, clipped to 04:00;
--   * a window that the 04:00-11:00 closure fully swallowed -> no slots (it never
--     took orders, and still does not).
-- Both channels stay ticked because the old code accepted pickup whenever it
-- accepted delivery. Managers can now untick either per slot.
-- Dine-in hours are the old opening/closing pair, for dine-in branches only.

-- AddColumns (additive, defaulted: every row is valid before the backfill)
ALTER TABLE "BranchBrand" ADD COLUMN "hours" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Branch" ADD COLUMN "dineInHours" TEXT NOT NULL DEFAULT '';

-- Backfill each brand's schedule from its branch's old hours.
UPDATE "BranchBrand"
SET "hours" = (
  SELECT
    CASE
      WHEN NOT h.valid THEN
        json_object('everyDay', json_array(json_object('start', '11:00', 'end', '04:00', 'delivery', json('true'), 'pickup', json('true'))), 'days', json_object())
      WHEN h.daytime AND NOT h.late AND h.c <= '11:00' THEN
        json_object('everyDay', json_array(), 'days', json_object())
      ELSE
        json_object('everyDay', json_array(json_object(
          'start', CASE WHEN h.o >= '04:00' AND h.o < '11:00' THEN '11:00' ELSE h.o END,
          'end', CASE
                   WHEN h.daytime AND h.late THEN '04:00'
                   WHEN h.daytime THEN h.c
                   WHEN h.c > '04:00' THEN '04:00'
                   ELSE h.c
                 END,
          'delivery', json('true'), 'pickup', json('true'))), 'days', json_object())
    END
  FROM (
    SELECT
      b."openingTime" AS o,
      b."closingTime" AS c,
      (br."slug" = 'cheez') AS late,
      (b."openingTime" GLOB '[0-2][0-9]:[0-5][0-9]' AND b."closingTime" GLOB '[0-2][0-9]:[0-5][0-9]'
        AND b."openingTime" <= '23:59' AND b."closingTime" <= '23:59' AND b."openingTime" <> b."closingTime") AS valid,
      (b."closingTime" > b."openingTime" AND b."openingTime" >= '04:00') AS daytime
    FROM "Branch" b, "Brand" br
    WHERE b."id" = "BranchBrand"."branchId" AND br."id" = "BranchBrand"."brandId"
  ) h
);

-- Display-only dine-in hours: the old pair, on dine-in branches that had one.
UPDATE "Branch"
SET "dineInHours" = json_object('everyDay', json_array(json_object('start', "openingTime", 'end', "closingTime")), 'days', json_object())
WHERE "businessType" = 'dine_in'
  AND "openingTime" GLOB '[0-2][0-9]:[0-5][0-9]' AND "closingTime" GLOB '[0-2][0-9]:[0-5][0-9]'
  AND "openingTime" <= '23:59' AND "closingTime" <= '23:59' AND "openingTime" <> "closingTime";

-- Drop openingTime/closingTime (RedefineTables, generated by prisma migrate diff).
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_Branch" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT NOT NULL DEFAULT '',
    "latitude" DECIMAL,
    "longitude" DECIMAL,
    "zoneId" INTEGER NOT NULL,
    "deliveryRadiusKm" DECIMAL NOT NULL DEFAULT 3.0,
    "deliveryFee" DECIMAL NOT NULL DEFAULT 0,
    "businessType" TEXT NOT NULL DEFAULT 'dine_in',
    "prepTimeMinutes" INTEGER NOT NULL DEFAULT 30,
    "pickupEnabled" BOOLEAN NOT NULL DEFAULT true,
    "pickupAddress" TEXT NOT NULL DEFAULT '',
    "pickupPhone" TEXT NOT NULL DEFAULT '',
    "bkashNumber" TEXT NOT NULL DEFAULT '',
    "bkashEnabled" BOOLEAN NOT NULL DEFAULT false,
    "bkashInstructions" TEXT NOT NULL DEFAULT '',
    "managerId" INTEGER,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "holdReason" TEXT NOT NULL DEFAULT '',
    "isArchived" BOOLEAN NOT NULL DEFAULT false,
    "archivedAt" DATETIME,
    "archivedById" INTEGER,
    "isOnHold" BOOLEAN NOT NULL DEFAULT false,
    "deliveryPauseMode" TEXT NOT NULL DEFAULT '',
    "deliveryPausedUntil" DATETIME,
    "deliveryPausedAt" DATETIME,
    "deliveryPausedById" INTEGER,
    "holdStartedAt" DATETIME,
    "holdStartedById" INTEGER,
    "holdReleaseReason" TEXT NOT NULL DEFAULT '',
    "holdReleasedAt" DATETIME,
    "holdReleasedById" INTEGER,
    "dineInHours" TEXT NOT NULL DEFAULT '',
    "logo" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Branch_zoneId_fkey" FOREIGN KEY ("zoneId") REFERENCES "DeliveryZone" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Branch_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_Branch" ("dineInHours", "address", "archivedAt", "archivedById", "bkashEnabled", "bkashInstructions", "bkashNumber", "businessType", "createdAt", "deliveryFee", "deliveryPauseMode", "deliveryPausedAt", "deliveryPausedById", "deliveryPausedUntil", "deliveryRadiusKm", "email", "holdReason", "holdReleaseReason", "holdReleasedAt", "holdReleasedById", "holdStartedAt", "holdStartedById", "id", "isActive", "isArchived", "isOnHold", "latitude", "logo", "longitude", "managerId", "name", "phone", "pickupAddress", "pickupEnabled", "pickupPhone", "prepTimeMinutes", "updatedAt", "zoneId") SELECT "dineInHours", "address", "archivedAt", "archivedById", "bkashEnabled", "bkashInstructions", "bkashNumber", "businessType", "createdAt", "deliveryFee", "deliveryPauseMode", "deliveryPausedAt", "deliveryPausedById", "deliveryPausedUntil", "deliveryRadiusKm", "email", "holdReason", "holdReleaseReason", "holdReleasedAt", "holdReleasedById", "holdStartedAt", "holdStartedById", "id", "isActive", "isArchived", "isOnHold", "latitude", "logo", "longitude", "managerId", "name", "phone", "pickupAddress", "pickupEnabled", "pickupPhone", "prepTimeMinutes", "updatedAt", "zoneId" FROM "Branch";
DROP TABLE "Branch";
ALTER TABLE "new_Branch" RENAME TO "Branch";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
